# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'displayBox.ui'
#
# Created: Fri Jul 25 18:00:48 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_displayBox(object):
    def setupUi(self, displayBox):
        displayBox.setObjectName("displayBox")
        displayBox.resize(267, 204)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(displayBox.sizePolicy().hasHeightForWidth())
        displayBox.setSizePolicy(sizePolicy)
        self.vboxlayout = QtGui.QVBoxLayout(displayBox)
        self.vboxlayout.setObjectName("vboxlayout")
        self.intensityHistogram = PlotWidget(displayBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.intensityHistogram.sizePolicy().hasHeightForWidth())
        self.intensityHistogram.setSizePolicy(sizePolicy)
        self.intensityHistogram.setMinimumSize(QtCore.QSize(0, 50))
        self.intensityHistogram.setMaximumSize(QtCore.QSize(300, 50))
        self.intensityHistogram.setObjectName("intensityHistogram")
        self.vboxlayout.addWidget(self.intensityHistogram)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtGui.QLabel(displayBox)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.displayMin = QtGui.QLineEdit(displayBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.displayMin.sizePolicy().hasHeightForWidth())
        self.displayMin.setSizePolicy(sizePolicy)
        self.displayMin.setMaximumSize(QtCore.QSize(75, 16777215))
        self.displayMin.setObjectName("displayMin")
        self.horizontalLayout.addWidget(self.displayMin)
        self.label_2 = QtGui.QLabel(displayBox)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.displayMax = QtGui.QLineEdit(displayBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.displayMax.sizePolicy().hasHeightForWidth())
        self.displayMax.setSizePolicy(sizePolicy)
        self.displayMax.setMaximumSize(QtCore.QSize(75, 16777215))
        self.displayMax.setObjectName("displayMax")
        self.horizontalLayout.addWidget(self.displayMax)
        self.vboxlayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.displayAutorange = QtGui.QCheckBox(displayBox)
        self.displayAutorange.setObjectName("displayAutorange")
        self.horizontalLayout_2.addWidget(self.displayAutorange)
        self.displayClamp = QtGui.QCheckBox(displayBox)
        self.displayClamp.setObjectName("displayClamp")
        self.horizontalLayout_2.addWidget(self.displayClamp)
        self.vboxlayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.displayScale = QtGui.QComboBox(displayBox)
        self.displayScale.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.displayScale.setObjectName("displayScale")
        self.displayScale.addItem("")
        self.displayScale.addItem("")
        self.displayScale.addItem("")
        self.horizontalLayout_3.addWidget(self.displayScale)
        self.displayColormap = QtGui.QPushButton(displayBox)
        self.displayColormap.setText("")
        self.displayColormap.setObjectName("displayColormap")
        self.horizontalLayout_3.addWidget(self.displayColormap)
        self.vboxlayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(displayBox)
        QtCore.QMetaObject.connectSlotsByName(displayBox)

    def retranslateUi(self, displayBox):
        displayBox.setWindowTitle(QtGui.QApplication.translate("displayBox", "GroupBox", None, QtGui.QApplication.UnicodeUTF8))
        displayBox.setTitle(QtGui.QApplication.translate("displayBox", "Display Properties", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("displayBox", "Min:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("displayBox", "Max:", None, QtGui.QApplication.UnicodeUTF8))
        self.displayAutorange.setText(QtGui.QApplication.translate("displayBox", "Autorange", None, QtGui.QApplication.UnicodeUTF8))
        self.displayClamp.setText(QtGui.QApplication.translate("displayBox", "Clamp", None, QtGui.QApplication.UnicodeUTF8))
        self.displayScale.setItemText(0, QtGui.QApplication.translate("displayBox", "Linear", None, QtGui.QApplication.UnicodeUTF8))
        self.displayScale.setItemText(1, QtGui.QApplication.translate("displayBox", "Logarithmic", None, QtGui.QApplication.UnicodeUTF8))
        self.displayScale.setItemText(2, QtGui.QApplication.translate("displayBox", "Power", None, QtGui.QApplication.UnicodeUTF8))

from pyqtgraph import PlotWidget
