#!/bin/bash
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
if [ "$(hostname)" == psusr* ] || [ "$(hostname)" == psnxserv ]
then
  # Source environment
  source $DIR/source_this_on_psusr
fi
# Arguments
if [ ! -z $1 ] 
then 
    ARG="$1"
else
    ARG=""
fi
# Start owl
$DIR/owl.py $ARG
