# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'experimentDialog.ui'
#
# Created: Tue Jul  8 09:54:22 2014
#      by: pyside-uic 0.2.14 running on PySide 1.1.2
#
# WARNING! All changes made in this file will be lost!

from Qt import QtCore, QtGui

class Ui_ExperimentDialog(object):
    def setupUi(self, ExperimentDialog):
        ExperimentDialog.setObjectName("ExperimentDialog")
        ExperimentDialog.resize(400, 308)
        self.verticalLayout = QtGui.QVBoxLayout(ExperimentDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtGui.QLabel(ExperimentDialog)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.wavelength = QtGui.QDoubleSpinBox(ExperimentDialog)
        self.wavelength.setDecimals(4)
        self.wavelength.setMaximum(100.0)
        self.wavelength.setSingleStep(0.1)
        self.wavelength.setProperty("value", 1.0)
        self.wavelength.setObjectName("wavelength")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.wavelength)
        self.label_2 = QtGui.QLabel(ExperimentDialog)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.energy = QtGui.QDoubleSpinBox(ExperimentDialog)
        self.energy.setDecimals(1)
        self.energy.setMaximum(100000.0)
        self.energy.setProperty("value", 1000.0)
        self.energy.setObjectName("energy")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.energy)
        self.label_3 = QtGui.QLabel(ExperimentDialog)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_3)
        self.distance = QtGui.QDoubleSpinBox(ExperimentDialog)
        self.distance.setDecimals(1)
        self.distance.setMaximum(100000.0)
        self.distance.setProperty("value", 100.0)
        self.distance.setObjectName("distance")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.distance)
        self.label_4 = QtGui.QLabel(ExperimentDialog)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_4)
        self.pixelSize = QtGui.QDoubleSpinBox(ExperimentDialog)
        self.pixelSize.setMaximum(10000.0)
        self.pixelSize.setProperty("value", 75.0)
        self.pixelSize.setObjectName("pixelSize")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.pixelSize)
        self.label_5 = QtGui.QLabel(ExperimentDialog)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_5)
        self.materialType = QtGui.QComboBox(ExperimentDialog)
        self.materialType.setObjectName("materialType")
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.materialType)
        self.label_6 = QtGui.QLabel(ExperimentDialog)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_6)
        self.quantumEfficiency = QtGui.QDoubleSpinBox(ExperimentDialog)
        self.quantumEfficiency.setMaximum(1.0)
        self.quantumEfficiency.setSingleStep(0.01)
        self.quantumEfficiency.setObjectName("quantumEfficiency")
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.quantumEfficiency)
        self.label_7 = QtGui.QLabel(ExperimentDialog)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_7)
        self.ADUPhoton = QtGui.QDoubleSpinBox(ExperimentDialog)
        self.ADUPhoton.setMaximum(10000.0)
        self.ADUPhoton.setObjectName("ADUPhoton")
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.ADUPhoton)
        self.verticalLayout.addLayout(self.formLayout)
        self.buttonBox = QtGui.QDialogButtonBox(ExperimentDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(ExperimentDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), ExperimentDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), ExperimentDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(ExperimentDialog)

    def retranslateUi(self, ExperimentDialog):
        ExperimentDialog.setWindowTitle(QtGui.QApplication.translate("ExperimentDialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("ExperimentDialog", "Photon wavelength [nm]", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("ExperimentDialog", "Photon energy [eV]", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("ExperimentDialog", "Detector distance [mm]", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("ExperimentDialog", "Detector pixel size [µm]", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("ExperimentDialog", "Sample material type", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("ExperimentDialog", "Detector quantum efficiency", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("ExperimentDialog", "Detector photon signal [a.d.u.]", None, QtGui.QApplication.UnicodeUTF8))

