# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/modelProperties.ui'
#
# Created: Wed Oct  1 16:03:41 2014
#      by: pyside-uic 0.2.13 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_ModelProperties(object):
    def setupUi(self, ModelProperties):
        ModelProperties.setObjectName("ModelProperties")
        ModelProperties.resize(258, 362)
        self.gridLayout_2 = QtGui.QGridLayout(ModelProperties)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtGui.QLabel(ModelProperties)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.centerX = QtGui.QDoubleSpinBox(ModelProperties)
        self.centerX.setMinimum(-10000.0)
        self.centerX.setMaximum(10000.0)
        self.centerX.setObjectName("centerX")
        self.gridLayout_2.addWidget(self.centerX, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(ModelProperties)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.centerY = QtGui.QDoubleSpinBox(ModelProperties)
        self.centerY.setMinimum(-10000.0)
        self.centerY.setMaximum(10000.0)
        self.centerY.setObjectName("centerY")
        self.gridLayout_2.addWidget(self.centerY, 1, 1, 1, 1)
        self.label_3 = QtGui.QLabel(ModelProperties)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 1)
        self.diameter = QtGui.QDoubleSpinBox(ModelProperties)
        self.diameter.setMaximum(10000.0)
        self.diameter.setSingleStep(5.0)
        self.diameter.setProperty("value", 100.0)
        self.diameter.setObjectName("diameter")
        self.gridLayout_2.addWidget(self.diameter, 2, 1, 1, 1)
        self.label_4 = QtGui.QLabel(ModelProperties)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 3, 0, 1, 1)
        self.scaling = QtGui.QDoubleSpinBox(ModelProperties)
        self.scaling.setDecimals(5)
        self.scaling.setMaximum(100.0)
        self.scaling.setSingleStep(0.1)
        self.scaling.setProperty("value", 1.0)
        self.scaling.setObjectName("scaling")
        self.gridLayout_2.addWidget(self.scaling, 3, 1, 1, 1)
        self.label_5 = QtGui.QLabel(ModelProperties)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 4, 0, 1, 1)
        self.maskRadius = QtGui.QSpinBox(ModelProperties)
        self.maskRadius.setMaximum(10000)
        self.maskRadius.setProperty("value", 100)
        self.maskRadius.setObjectName("maskRadius")
        self.gridLayout_2.addWidget(self.maskRadius, 4, 1, 1, 1)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.visibilitySlider = QtGui.QSlider(ModelProperties)
        self.visibilitySlider.setMinimum(-1)
        self.visibilitySlider.setMaximum(101)
        self.visibilitySlider.setProperty("value", 50)
        self.visibilitySlider.setOrientation(QtCore.Qt.Horizontal)
        self.visibilitySlider.setObjectName("visibilitySlider")
        self.gridLayout.addWidget(self.visibilitySlider, 0, 0, 1, 2)
        self.experiment = QtGui.QPushButton(ModelProperties)
        self.experiment.setObjectName("experiment")
        self.gridLayout.addWidget(self.experiment, 1, 0, 1, 2)
        self.findCenterPushButton = QtGui.QPushButton(ModelProperties)
        self.findCenterPushButton.setObjectName("findCenterPushButton")
        self.gridLayout.addWidget(self.findCenterPushButton, 2, 0, 1, 1)
        self.findRadiusPushButton = QtGui.QPushButton(ModelProperties)
        self.findRadiusPushButton.setObjectName("findRadiusPushButton")
        self.gridLayout.addWidget(self.findRadiusPushButton, 2, 1, 1, 1)
        self.fitModelPushButton = QtGui.QPushButton(ModelProperties)
        self.fitModelPushButton.setObjectName("fitModelPushButton")
        self.gridLayout.addWidget(self.fitModelPushButton, 3, 0, 1, 2)
        self.gridLayout_2.addLayout(self.gridLayout, 5, 0, 1, 2)

        self.retranslateUi(ModelProperties)
        QtCore.QMetaObject.connectSlotsByName(ModelProperties)

    def retranslateUi(self, ModelProperties):
        ModelProperties.setWindowTitle(QtGui.QApplication.translate("ModelProperties", "Model Properties", None, QtGui.QApplication.UnicodeUTF8))
        ModelProperties.setTitle(QtGui.QApplication.translate("ModelProperties", "Model Properties", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("ModelProperties", "Center X [px]:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("ModelProperties", "Center Y [px]:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("ModelProperties", "Diameter [nm]:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("ModelProperties", "Intensity [mJ/µm2]:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("ModelProperties", "Mask radius [px]:", None, QtGui.QApplication.UnicodeUTF8))
        self.experiment.setText(QtGui.QApplication.translate("ModelProperties", "Experiment...", None, QtGui.QApplication.UnicodeUTF8))
        self.findCenterPushButton.setText(QtGui.QApplication.translate("ModelProperties", "Find center", None, QtGui.QApplication.UnicodeUTF8))
        self.findRadiusPushButton.setText(QtGui.QApplication.translate("ModelProperties", "Find radius", None, QtGui.QApplication.UnicodeUTF8))
        self.fitModelPushButton.setText(QtGui.QApplication.translate("ModelProperties", "Fit model", None, QtGui.QApplication.UnicodeUTF8))

