# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/modelProperties.ui'
#
# Created: Tue Nov  4 16:05:31 2014
#      by: pyside-uic 0.2.13 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_ModelProperties(object):
    def setupUi(self, ModelProperties):
        ModelProperties.setObjectName("ModelProperties")
        ModelProperties.resize(255, 493)
        ModelProperties.setStyleSheet("Text-align:left")
        self.gridLayout_4 = QtGui.QGridLayout(ModelProperties)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.experiment = QtGui.QPushButton(ModelProperties)
        self.experiment.setStyleSheet("Text-align:center")
        self.experiment.setObjectName("experiment")
        self.gridLayout_4.addWidget(self.experiment, 0, 0, 1, 1)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.centerXLabel = QtGui.QLabel(ModelProperties)
        self.centerXLabel.setObjectName("centerXLabel")
        self.gridLayout_2.addWidget(self.centerXLabel, 0, 0, 1, 1)
        self.centerX = QtGui.QDoubleSpinBox(ModelProperties)
        self.centerX.setMinimum(-10000.0)
        self.centerX.setMaximum(10000.0)
        self.centerX.setObjectName("centerX")
        self.gridLayout_2.addWidget(self.centerX, 0, 1, 1, 1)
        self.centerYLabel = QtGui.QLabel(ModelProperties)
        self.centerYLabel.setObjectName("centerYLabel")
        self.gridLayout_2.addWidget(self.centerYLabel, 1, 0, 1, 1)
        self.centerY = QtGui.QDoubleSpinBox(ModelProperties)
        self.centerY.setMinimum(-10000.0)
        self.centerY.setMaximum(10000.0)
        self.centerY.setObjectName("centerY")
        self.gridLayout_2.addWidget(self.centerY, 1, 1, 1, 1)
        self.diameterLabel = QtGui.QLabel(ModelProperties)
        self.diameterLabel.setObjectName("diameterLabel")
        self.gridLayout_2.addWidget(self.diameterLabel, 2, 0, 1, 1)
        self.diameter = QtGui.QDoubleSpinBox(ModelProperties)
        self.diameter.setMaximum(10000.0)
        self.diameter.setSingleStep(5.0)
        self.diameter.setProperty("value", 100.0)
        self.diameter.setObjectName("diameter")
        self.gridLayout_2.addWidget(self.diameter, 2, 1, 1, 1)
        self.intensityLabel = QtGui.QLabel(ModelProperties)
        self.intensityLabel.setObjectName("intensityLabel")
        self.gridLayout_2.addWidget(self.intensityLabel, 3, 0, 1, 1)
        self.intensity = QtGui.QDoubleSpinBox(ModelProperties)
        self.intensity.setDecimals(5)
        self.intensity.setMaximum(100.0)
        self.intensity.setSingleStep(0.1)
        self.intensity.setProperty("value", 1.0)
        self.intensity.setObjectName("intensity")
        self.gridLayout_2.addWidget(self.intensity, 3, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_2, 1, 0, 1, 1)
        self.visibilitySlider = QtGui.QSlider(ModelProperties)
        self.visibilitySlider.setMinimum(-1)
        self.visibilitySlider.setMaximum(101)
        self.visibilitySlider.setProperty("value", 50)
        self.visibilitySlider.setOrientation(QtCore.Qt.Horizontal)
        self.visibilitySlider.setObjectName("visibilitySlider")
        self.gridLayout_4.addWidget(self.visibilitySlider, 2, 0, 1, 1)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_5 = QtGui.QLabel(ModelProperties)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 0, 0, 1, 1)
        self.maskRadius = QtGui.QSpinBox(ModelProperties)
        self.maskRadius.setMaximum(10000)
        self.maskRadius.setProperty("value", 100)
        self.maskRadius.setObjectName("maskRadius")
        self.gridLayout_3.addWidget(self.maskRadius, 0, 1, 1, 2)
        self.label_7 = QtGui.QLabel(ModelProperties)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 2, 0, 1, 1)
        self.blurRadius = QtGui.QDoubleSpinBox(ModelProperties)
        self.blurRadius.setDecimals(2)
        self.blurRadius.setProperty("value", 4.0)
        self.blurRadius.setObjectName("blurRadius")
        self.gridLayout_3.addWidget(self.blurRadius, 2, 1, 1, 2)
        self.label_6 = QtGui.QLabel(ModelProperties)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 1, 0, 1, 1)
        self.maximumShift = QtGui.QDoubleSpinBox(ModelProperties)
        self.maximumShift.setDecimals(0)
        self.maximumShift.setProperty("value", 5.0)
        self.maximumShift.setObjectName("maximumShift")
        self.gridLayout_3.addWidget(self.maximumShift, 1, 1, 1, 2)
        self.gridLayout_4.addLayout(self.gridLayout_3, 3, 0, 1, 1)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.findCenterMethod = QtGui.QComboBox(ModelProperties)
        self.findCenterMethod.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.findCenterMethod.sizePolicy().hasHeightForWidth())
        self.findCenterMethod.setSizePolicy(sizePolicy)
        self.findCenterMethod.setObjectName("findCenterMethod")
        self.findCenterMethod.addItem("")
        self.findCenterMethod.addItem("")
        self.findCenterMethod.addItem("")
        self.findCenterMethod.addItem("")
        self.findCenterMethod.addItem("")
        self.gridLayout.addWidget(self.findCenterMethod, 0, 0, 1, 1)
        self.findCenterPushButton = QtGui.QPushButton(ModelProperties)
        self.findCenterPushButton.setObjectName("findCenterPushButton")
        self.gridLayout.addWidget(self.findCenterPushButton, 0, 1, 1, 1)
        self.fitDiameterMethod = QtGui.QComboBox(ModelProperties)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fitDiameterMethod.sizePolicy().hasHeightForWidth())
        self.fitDiameterMethod.setSizePolicy(sizePolicy)
        self.fitDiameterMethod.setObjectName("fitDiameterMethod")
        self.fitDiameterMethod.addItem("")
        self.fitDiameterMethod.addItem("")
        self.gridLayout.addWidget(self.fitDiameterMethod, 1, 0, 1, 1)
        self.fitDiameterPushButton = QtGui.QPushButton(ModelProperties)
        self.fitDiameterPushButton.setObjectName("fitDiameterPushButton")
        self.gridLayout.addWidget(self.fitDiameterPushButton, 1, 1, 1, 1)
        self.fitIntensityMethod = QtGui.QComboBox(ModelProperties)
        self.fitIntensityMethod.setObjectName("fitIntensityMethod")
        self.fitIntensityMethod.addItem("")
        self.fitIntensityMethod.addItem("")
        self.gridLayout.addWidget(self.fitIntensityMethod, 2, 0, 1, 1)
        self.fitIntensityPushButton = QtGui.QPushButton(ModelProperties)
        self.fitIntensityPushButton.setObjectName("fitIntensityPushButton")
        self.gridLayout.addWidget(self.fitIntensityPushButton, 2, 1, 1, 1)
        self.fitModelMethod = QtGui.QComboBox(ModelProperties)
        self.fitModelMethod.setObjectName("fitModelMethod")
        self.fitModelMethod.addItem("")
        self.fitModelMethod.addItem("")
        self.gridLayout.addWidget(self.fitModelMethod, 3, 0, 1, 1)
        self.fitModelPushButton = QtGui.QPushButton(ModelProperties)
        self.fitModelPushButton.setObjectName("fitModelPushButton")
        self.gridLayout.addWidget(self.fitModelPushButton, 3, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout, 4, 0, 1, 1)

        self.retranslateUi(ModelProperties)
        QtCore.QMetaObject.connectSlotsByName(ModelProperties)

    def retranslateUi(self, ModelProperties):
        ModelProperties.setWindowTitle(QtGui.QApplication.translate("ModelProperties", "Model Properties", None, QtGui.QApplication.UnicodeUTF8))
        ModelProperties.setTitle(QtGui.QApplication.translate("ModelProperties", "Model Properties", None, QtGui.QApplication.UnicodeUTF8))
        self.experiment.setText(QtGui.QApplication.translate("ModelProperties", "Experiment...", None, QtGui.QApplication.UnicodeUTF8))
        self.centerXLabel.setText(QtGui.QApplication.translate("ModelProperties", "Center X [px]:", None, QtGui.QApplication.UnicodeUTF8))
        self.centerYLabel.setText(QtGui.QApplication.translate("ModelProperties", "Center Y [px]:", None, QtGui.QApplication.UnicodeUTF8))
        self.diameterLabel.setText(QtGui.QApplication.translate("ModelProperties", "Diameter [nm]:", None, QtGui.QApplication.UnicodeUTF8))
        self.intensityLabel.setText(QtGui.QApplication.translate("ModelProperties", "Intensity [mJ/µm2]:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("ModelProperties", "Mask radius [px]:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("ModelProperties", "Blur radius [px]:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("ModelProperties", "Maximum shift [px]:", None, QtGui.QApplication.UnicodeUTF8))
        self.findCenterMethod.setItemText(0, QtGui.QApplication.translate("ModelProperties", "none", None, QtGui.QApplication.UnicodeUTF8))
        self.findCenterMethod.setItemText(1, QtGui.QApplication.translate("ModelProperties", "quadrant", None, QtGui.QApplication.UnicodeUTF8))
        self.findCenterMethod.setItemText(2, QtGui.QApplication.translate("ModelProperties", "blurred", None, QtGui.QApplication.UnicodeUTF8))
        self.findCenterMethod.setItemText(3, QtGui.QApplication.translate("ModelProperties", "pw (fast)", None, QtGui.QApplication.UnicodeUTF8))
        self.findCenterMethod.setItemText(4, QtGui.QApplication.translate("ModelProperties", "pw (slow)", None, QtGui.QApplication.UnicodeUTF8))
        self.findCenterPushButton.setText(QtGui.QApplication.translate("ModelProperties", "Find center", None, QtGui.QApplication.UnicodeUTF8))
        self.fitDiameterMethod.setItemText(0, QtGui.QApplication.translate("ModelProperties", "pearson", None, QtGui.QApplication.UnicodeUTF8))
        self.fitDiameterMethod.setItemText(1, QtGui.QApplication.translate("ModelProperties", "none", None, QtGui.QApplication.UnicodeUTF8))
        self.fitDiameterPushButton.setText(QtGui.QApplication.translate("ModelProperties", "Fit diameter", None, QtGui.QApplication.UnicodeUTF8))
        self.fitIntensityMethod.setItemText(0, QtGui.QApplication.translate("ModelProperties", "simple", None, QtGui.QApplication.UnicodeUTF8))
        self.fitIntensityMethod.setItemText(1, QtGui.QApplication.translate("ModelProperties", "none", None, QtGui.QApplication.UnicodeUTF8))
        self.fitIntensityPushButton.setText(QtGui.QApplication.translate("ModelProperties", "Fit intensity", None, QtGui.QApplication.UnicodeUTF8))
        self.fitModelMethod.setItemText(0, QtGui.QApplication.translate("ModelProperties", "fast", None, QtGui.QApplication.UnicodeUTF8))
        self.fitModelMethod.setItemText(1, QtGui.QApplication.translate("ModelProperties", "refine", None, QtGui.QApplication.UnicodeUTF8))
        self.fitModelPushButton.setText(QtGui.QApplication.translate("ModelProperties", "Fit model", None, QtGui.QApplication.UnicodeUTF8))

