# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'preferencesDialog.ui'
#
# Created: Mon Sep 29 17:24:55 2014
#      by: pyside-uic 0.2.13 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from Qt import QtCore, QtGui

class Ui_PreferencesDialog(object):
    def setupUi(self, PreferencesDialog):
        PreferencesDialog.setObjectName("PreferencesDialog")
        PreferencesDialog.resize(449, 291)
        self.verticalLayout = QtGui.QVBoxLayout(PreferencesDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtGui.QTabWidget(PreferencesDialog)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_5 = QtGui.QGridLayout(self.tab_3)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.shortcutsTable = QtGui.QTableWidget(self.tab_3)
        self.shortcutsTable.setAlternatingRowColors(False)
        self.shortcutsTable.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.shortcutsTable.setRowCount(11)
        self.shortcutsTable.setObjectName("shortcutsTable")
        self.shortcutsTable.setColumnCount(1)
        self.shortcutsTable.setRowCount(11)
        item = QtGui.QTableWidgetItem()
        self.shortcutsTable.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.shortcutsTable.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.shortcutsTable.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.shortcutsTable.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.shortcutsTable.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.shortcutsTable.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.shortcutsTable.setVerticalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.shortcutsTable.setVerticalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.shortcutsTable.setVerticalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.shortcutsTable.setVerticalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.shortcutsTable.setVerticalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.shortcutsTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEnabled)
        self.shortcutsTable.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEnabled)
        self.shortcutsTable.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEnabled)
        self.shortcutsTable.setItem(2, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEnabled)
        self.shortcutsTable.setItem(3, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEnabled)
        self.shortcutsTable.setItem(4, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEnabled)
        self.shortcutsTable.setItem(5, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEnabled)
        self.shortcutsTable.setItem(6, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEnabled)
        self.shortcutsTable.setItem(7, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEnabled)
        self.shortcutsTable.setItem(8, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEnabled)
        self.shortcutsTable.setItem(9, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEnabled)
        self.shortcutsTable.setItem(10, 0, item)
        self.shortcutsTable.horizontalHeader().setVisible(False)
        self.shortcutsTable.horizontalHeader().setDefaultSectionSize(350)
        self.shortcutsTable.horizontalHeader().setStretchLastSection(True)
        self.gridLayout_5.addWidget(self.shortcutsTable, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout = QtGui.QGridLayout(self.tab)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        self.label = QtGui.QLabel(self.tab)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.PNGOutputPath = QtGui.QLineEdit(self.tab)
        self.PNGOutputPath.setObjectName("PNGOutputPath")
        self.gridLayout.addWidget(self.PNGOutputPath, 1, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 2, 1, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_3 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 3, 0, 3, 1)
        self.label_4 = QtGui.QLabel(self.tab_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 4, 1, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem3, 3, 3, 3, 1)
        self.textureCacheSpin = QtGui.QSpinBox(self.tab_2)
        self.textureCacheSpin.setMaximum(1073741824)
        self.textureCacheSpin.setSingleStep(128)
        self.textureCacheSpin.setProperty("value", 256)
        self.textureCacheSpin.setObjectName("textureCacheSpin")
        self.gridLayout_3.addWidget(self.textureCacheSpin, 8, 2, 1, 1)
        self.geometryCacheSpin = QtGui.QSpinBox(self.tab_2)
        self.geometryCacheSpin.setMaximum(1073741824)
        self.geometryCacheSpin.setSingleStep(512)
        self.geometryCacheSpin.setProperty("value", 10)
        self.geometryCacheSpin.setObjectName("geometryCacheSpin")
        self.gridLayout_3.addWidget(self.geometryCacheSpin, 6, 2, 1, 1)
        self.maskCacheSpin = QtGui.QSpinBox(self.tab_2)
        self.maskCacheSpin.setMaximum(1073741824)
        self.maskCacheSpin.setSingleStep(512)
        self.maskCacheSpin.setProperty("value", 1024)
        self.maskCacheSpin.setObjectName("maskCacheSpin")
        self.gridLayout_3.addWidget(self.maskCacheSpin, 3, 2, 3, 1)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem4, 9, 2, 1, 1)
        self.label_5 = QtGui.QLabel(self.tab_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 8, 1, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem5, 0, 2, 1, 1)
        self.label_15 = QtGui.QLabel(self.tab_2)
        self.label_15.setObjectName("label_15")
        self.gridLayout_3.addWidget(self.label_15, 6, 1, 1, 1)
        self.imageCacheSpin = QtGui.QSpinBox(self.tab_2)
        self.imageCacheSpin.setMaximum(1073741824)
        self.imageCacheSpin.setSingleStep(512)
        self.imageCacheSpin.setProperty("value", 1024)
        self.imageCacheSpin.setObjectName("imageCacheSpin")
        self.gridLayout_3.addWidget(self.imageCacheSpin, 2, 2, 1, 1)
        self.label_3 = QtGui.QLabel(self.tab_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 2, 1, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.formLayout = QtGui.QFormLayout(self.tab_5)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.FieldsStayAtSizeHint)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtGui.QLabel(self.tab_5)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_2)
        self.label_9 = QtGui.QLabel(self.tab_5)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_9)
        self.modelCenterX = QtGui.QLineEdit(self.tab_5)
        self.modelCenterX.setObjectName("modelCenterX")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.modelCenterX)
        self.label_10 = QtGui.QLabel(self.tab_5)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_10)
        self.modelCenterY = QtGui.QLineEdit(self.tab_5)
        self.modelCenterY.setObjectName("modelCenterY")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.modelCenterY)
        self.label_11 = QtGui.QLabel(self.tab_5)
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_11)
        self.modelDiameter = QtGui.QLineEdit(self.tab_5)
        self.modelDiameter.setObjectName("modelDiameter")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.modelDiameter)
        self.label_12 = QtGui.QLabel(self.tab_5)
        self.label_12.setObjectName("label_12")
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_12)
        self.modelIntensity = QtGui.QLineEdit(self.tab_5)
        self.modelIntensity.setObjectName("modelIntensity")
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.modelIntensity)
        self.label_13 = QtGui.QLabel(self.tab_5)
        self.label_13.setObjectName("label_13")
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_13)
        self.modelMaskRadius = QtGui.QLineEdit(self.tab_5)
        self.modelMaskRadius.setObjectName("modelMaskRadius")
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.modelMaskRadius)
        self.label_14 = QtGui.QLabel(self.tab_5)
        self.label_14.setObjectName("label_14")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.label_14)
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_2 = QtGui.QGridLayout(self.tab_4)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_7 = QtGui.QLabel(self.tab_4)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 2, 1, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem6, 4, 1, 1, 1)
        self.updateTimerSpin = QtGui.QSpinBox(self.tab_4)
        self.updateTimerSpin.setMaximum(86400000)
        self.updateTimerSpin.setSingleStep(1000)
        self.updateTimerSpin.setProperty("value", 10000)
        self.updateTimerSpin.setObjectName("updateTimerSpin")
        self.gridLayout_2.addWidget(self.updateTimerSpin, 1, 2, 1, 1)
        self.label_6 = QtGui.QLabel(self.tab_4)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 1, 1, 1, 1)
        self.movingAverageSizeSpin = QtGui.QSpinBox(self.tab_4)
        self.movingAverageSizeSpin.setMaximum(86400000)
        self.movingAverageSizeSpin.setProperty("value", 10)
        self.movingAverageSizeSpin.setObjectName("movingAverageSizeSpin")
        self.gridLayout_2.addWidget(self.movingAverageSizeSpin, 2, 2, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem7, 1, 3, 1, 1)
        spacerItem8 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem8, 0, 1, 1, 1)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem9, 2, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.tab_4)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 3, 1, 1, 1)
        self.traditional = QtGui.QRadioButton(self.tab_4)
        self.traditional.setChecked(True)
        self.traditional.setObjectName("traditional")
        self.gridLayout_2.addWidget(self.traditional, 3, 2, 1, 1)
        self.natural = QtGui.QRadioButton(self.tab_4)
        self.natural.setObjectName("natural")
        self.gridLayout_2.addWidget(self.natural, 4, 2, 1, 1)
        self.tabWidget.addTab(self.tab_4, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.buttonBox = QtGui.QDialogButtonBox(PreferencesDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(PreferencesDialog)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), PreferencesDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), PreferencesDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(PreferencesDialog)

    def retranslateUi(self, PreferencesDialog):
        PreferencesDialog.setWindowTitle(QtGui.QApplication.translate("PreferencesDialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.shortcutsTable.verticalHeaderItem(0).setText(QtGui.QApplication.translate("PreferencesDialog", "Move Selection Right", None, QtGui.QApplication.UnicodeUTF8))
        self.shortcutsTable.verticalHeaderItem(1).setText(QtGui.QApplication.translate("PreferencesDialog", "Move Selection Left", None, QtGui.QApplication.UnicodeUTF8))
        self.shortcutsTable.verticalHeaderItem(2).setText(QtGui.QApplication.translate("PreferencesDialog", "Move Selection Up", None, QtGui.QApplication.UnicodeUTF8))
        self.shortcutsTable.verticalHeaderItem(3).setText(QtGui.QApplication.translate("PreferencesDialog", "Move Selection Down", None, QtGui.QApplication.UnicodeUTF8))
        self.shortcutsTable.verticalHeaderItem(4).setText(QtGui.QApplication.translate("PreferencesDialog", "Toggle 1st Tag", None, QtGui.QApplication.UnicodeUTF8))
        self.shortcutsTable.verticalHeaderItem(5).setText(QtGui.QApplication.translate("PreferencesDialog", "Toggle 2nd Tag", None, QtGui.QApplication.UnicodeUTF8))
        self.shortcutsTable.verticalHeaderItem(6).setText(QtGui.QApplication.translate("PreferencesDialog", "Toggle 3rd Tag", None, QtGui.QApplication.UnicodeUTF8))
        self.shortcutsTable.verticalHeaderItem(7).setText(QtGui.QApplication.translate("PreferencesDialog", "Toggle 4th Tag", None, QtGui.QApplication.UnicodeUTF8))
        self.shortcutsTable.verticalHeaderItem(8).setText(QtGui.QApplication.translate("PreferencesDialog", "Toggle 5th Tag", None, QtGui.QApplication.UnicodeUTF8))
        self.shortcutsTable.verticalHeaderItem(9).setText(QtGui.QApplication.translate("PreferencesDialog", "Toggle 6th Tag", None, QtGui.QApplication.UnicodeUTF8))
        self.shortcutsTable.verticalHeaderItem(10).setText(QtGui.QApplication.translate("PreferencesDialog", "Toggle 7th Tag", None, QtGui.QApplication.UnicodeUTF8))
        self.shortcutsTable.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("PreferencesDialog", "Shortcut", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.shortcutsTable.isSortingEnabled()
        self.shortcutsTable.setSortingEnabled(False)
        self.shortcutsTable.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("PreferencesDialog", "Shortcuts", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("PreferencesDialog", "PNG output path:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("PreferencesDialog", "Paths", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("PreferencesDialog", "Mask Cache (in MB):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("PreferencesDialog", "Texture Cache (in MB):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("PreferencesDialog", "Geometry Cache (in MB):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("PreferencesDialog", "Image Cache (in MB):", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("PreferencesDialog", "Caches", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("PreferencesDialog", "Default Values ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("PreferencesDialog", "Center X [px]:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("PreferencesDialog", "Center Y [px]:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("PreferencesDialog", "Diameter [nm]:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("PreferencesDialog", "Intensity [mj/µm2]:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("PreferencesDialog", "Mask Radius [px]:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("PreferencesDialog", "(requires restarting to take effect)", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), QtGui.QApplication.translate("PreferencesDialog", "Model", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("PreferencesDialog", "Moving average window size:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("PreferencesDialog", "Auto update timer (in ms):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("PreferencesDialog", "Scroll direction:", None, QtGui.QApplication.UnicodeUTF8))
        self.traditional.setText(QtGui.QApplication.translate("PreferencesDialog", "Traditional (PC)", None, QtGui.QApplication.UnicodeUTF8))
        self.natural.setText(QtGui.QApplication.translate("PreferencesDialog", "Natural (Mac)", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QtGui.QApplication.translate("PreferencesDialog", "Others", None, QtGui.QApplication.UnicodeUTF8))

